# Generated by Django 3.2.7 on 2021-09-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Ad')),
                ('category', models.CharField(choices=[('beauty', 'Gözəllik'), ('clothing', 'Geyim'), ('jewellery', 'Daş-qaş'), ('painting', 'Rəsm'), ('photography', 'Foto'), ('food', 'Yemək'), ('sport', 'İdman'), ('toy', 'Oyuncaq'), ('other', 'Digər')], max_length=50, verbose_name='Kateqoriya')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Yazı')),
                ('price', models.FloatField(verbose_name='Qiyməti')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('publishing_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım tarixi')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Məlumat')),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='magaza.magaza')),
            ],
        ),
    ]
